PersonasFisicasPrueba/Areas/Main/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PersonasFisicasPrueba.Areas.Main.Controllers
{
    [Area("Main")]
    public class MainController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PersonasFisicasPrueba/Areas/Main/Controllers/PerFisicasController.cs
using Microsoft.AspNetCore.Mvc;
using PersonasFisicasPrueba.Datos.Repository;
using PersonasFisicasPrueba.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace PersonasFisicasPrueba.Areas.Main.Controllers
{
    [Area("Main")]
    public class PerFisicasController : Controller
    {
        private readonly IUnitOfWork unidadTrabajo;

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public PerFisicasController(IUnitOfWork unit)
        {
            unidadTrabajo = unit;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(TbPersonasFisicas ins)
        {
            if (ModelState.IsValid)
            {
                ins.Activo = false;
                unidadTrabajo.PersonasFisicasR.Add(ins);
                unidadTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("Create");
        }

        [HttpGet]
        public IActionResult GetAllAPI()
        {
            Thread.Sleep(1000);
            return Json(new { data = unidadTrabajo.PersonasFisicasR.GetAll() });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            TbPersonasFisicas personas = unidadTrabajo.PersonasFisicasR.Get(id);
            if (personas == null)
            {
                return Json(new { success = false, message = "El persona fisica no existe" });
            }
            unidadTrabajo.PersonasFisicasR.Remove(personas);
            unidadTrabajo.Save();
            return Json(new { success = true, message = "Persona eliminada correctamente" });
        }

        [HttpPost]
        public IActionResult Update(TbPersonasFisicas personas)
        {
            if (ModelState.IsValid)
            {
                unidadTrabajo.PersonasFisicasR.Update(personas);
                unidadTrabajo.Save();
                return RedirectToAction(nameof(Index));
            }
            return View("Edit", personas);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            TbPersonasFisicas personas = unidadTrabajo.PersonasFisicasR.Get(id);
            if (personas == null)
            {
                return NotFound();
            }
            return View(personas);
        }

    }
}

PersonasFisicasPrueba/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PersonasFisicasPrueba.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace PersonasFisicasPrueba.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PersonasFisicasPrueba/Areas/Main/Views/Main/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index del Main</h1>

PersonasFisicasPrueba/Areas/Main/Views/PerFisicas/Create.cshtml
@model TbPersonasFisicas
 
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="text-center">Agregar Persona Fisica</h3>
<hr />

<form method="post" asp-area="Main" asp-controller="PerFisicas" asp-action="Insert">
    <div class="row px-2 mx-2 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Nombre"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ApellidoPaterno"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ApellidoPaterno" class="form-control" />
                    <span asp-validation-for="ApellidoPaterno" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ApellidoMaterno"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ApellidoMaterno" class="form-control" />
                    <span asp-validation-for="ApellidoMaterno" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaRegistro"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaRegistro" class="form-control" />
                    <span asp-validation-for="FechaRegistro" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaActualizacion"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaActualizacion" class="form-control" />
                    <span asp-validation-for="FechaActualizacion" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Rfc"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Rfc" class="form-control" />
                    <span asp-validation-for="Rfc" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaNacimiento"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="UsuarioAgrega"></label>
                </div>
                <div class="col-8">
                    <input asp-for="UsuarioAgrega" class="form-control" />
                    <span asp-validation-for="UsuarioAgrega" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-8 offset-4">
                    <partial name="VistaVolverCrear" />
                </div>
            </div>

        </div>
    </div>
</form>

PersonasFisicasPrueba/Areas/Main/Views/PerFisicas/Edit.cshtml
@model TbPersonasFisicas
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3 class="text-center">Editar Persona Fisica</h3>
<hr />

<form method="post" asp-area="Main" asp-controller="PerFisicas" asp-action="Update">
    <div class="row px-2 mx-2 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-10 offset-1 mt-4">


            <input type="hidden" asp-for="IdPersonaFisica" />

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaRegistro"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaRegistro" class="form-control" />
                    <span asp-validation-for="FechaRegistro" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaActualizacion"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaActualizacion" class="form-control" />
                    <span asp-validation-for="FechaActualizacion" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Nombre"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Nombre" class="form-control" />
                    <span asp-validation-for="Nombre" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ApellidoPaterno"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ApellidoPaterno" class="form-control" />
                    <span asp-validation-for="ApellidoPaterno" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="ApellidoMaterno"></label>
                </div>
                <div class="col-8">
                    <input asp-for="ApellidoMaterno" class="form-control" />
                    <span asp-validation-for="ApellidoMaterno" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="Rfc"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Rfc" class="form-control" />
                    <span asp-validation-for="Rfc" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="FechaNacimiento"></label>
                </div>
                <div class="col-8">
                    <input asp-for="FechaNacimiento" class="form-control" />
                    <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-4">
                    <label asp-for="UsuarioAgrega"></label>
                </div>
                <div class="col-8">
                    <input asp-for="UsuarioAgrega" class="form-control" />
                    <span asp-validation-for="UsuarioAgrega" class="text-danger"></span>
                </div>
            </div>


            <div class="form-group row">
                <div class="col-8 offset-4">
                    <partial name="VistaVolverCrear" />
                </div>
            </div>

        </div>
    </div>
</form>

PersonasFisicasPrueba/Areas/Main/Views/PerFisicas/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">

    <div class="col-6">
        <h2>Listado de Personas Fisicas</h2>
    </div>

    <div class="col-6">
        <a asp-area="Main" asp-controller="PerFisicas" asp-action="Create" class="btn btn-success">
            Agregar Persona Fisica
        </a>
    </div>

</div>





<table id="tblPersona" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>IdPersonaFisica</th>
            <th>Fecha de Registro</th>
            <th>Fecha Actualizacion</th>
            <th>Nombre completo</th>
            <th>RFC</th>
            <th>FechaNacimiento</th>
            <th>Usuario Agregado</th>
         
            <th>Acciones</th>
        </tr>
    </thead>
</table>

@section Scripts{


    <script src="~/js/persona.js"></script>
}

PersonasFisicasPrueba/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PersonasFisicasPrueba/Views/Shared/VistaVolverCrear.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">
            Guardar Cambios
        </button>
        &nbsp;
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">
            Volver a la Lista
        </a>
    </div>
</div>

PersonasFisicasPrueba/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PersonasFisicasPrueba</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PersonasFisicasPrueba</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Main" asp-controller="PerFisicas" asp-action="Index">PersonasFisicas</a>
                        </li>
                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - PersonasFisicasPrueba - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>